### PR TITLE
Support Signify-based signatures

### PR DESCRIPTION
**Pull request by romanz**
Following the discussion here: https://twitter.com/jb55/status/1151874791860629505.

Usage:
```
$ trezor-signify init JohnDoe
$ trezor-signify sign JohnDoe -m blob.txt
$ signify-openbsd -V -p JohnDoe.pub -m blob.txt
```

### CODE REVIEW

**Comment by jb55** [comment]
nice, testing this now

**Comment by romanz** [comment]
Thanks, pushed a fix above :)

**Comment by romanz** [comment]
The only issue left is that Signify assumes enough memory for the entire message to be signed, IIUC.
This can be handled by SHA256-ing the input and signing the resulting digest, i.e. using `signify -C` flag:
```
-C          Verify a signed checksum list, and then verify the checksum for each file.  If no files are specified, all of them are checked.  sigfile should be the signed output of sha256(1).
```

**Comment by romanz** [comment]
The PR seems to work well on TREZOR model T, with 16k input:
```
$ trezor-signify pubkey 'John Doe' | tee pubkey
untrusted comment: identity <signify://John Doe|ed25519>
RWT8wWc9mbxaBufJp/+qf3euagfQGDda/CSN687lLchrqKTfZfpXBOlB

$ dd if=/dev/urandom of=message bs=1 count=16k
16384+0 records in
16384+0 records out
16384 bytes (16 kB, 16 KiB) copied, 0.0377085 s, 434 kB/s

$ trezor-signify sign 'John Doe' | tee message.sig
untrusted comment: pubkey RWT8wWc9mbxaBufJp/+qf3euagfQGDda/CSN687lLchrqKTfZfpXBOlB
RWT8wWc9mbxaBtzadqRB7Ya4u6upxdiXJmypjS4wVpveqrXkxdxB6ZIGmpitPOLcPwUvoT/tBASgWKTgU1LB+X71L7U2Tqem9gc=

$ signify-openbsd -V -p pubkey -x message.sig -m-
Signature Verified

```

**Comment by jb55** [comment]
Roman Zeyde <notifications@github.com> writes:
> Merged #293 into master.

great! thanks Roman!

**Pull request merged**
