### PR TITLE
Allow contents in buffer when using _legacy_pubs

### PR DESCRIPTION
**Pull request by nubis**
Hi,
I'm trying to use trezor-agent to automate deploys via capistrano in a rails app.
In case you're not familiar with it, Capistrano is a tool that uses a pure-ruby SSH client library to connect to servers and perform tasks on them. It uses non-interactive / non-login shells.

When running capistrano inside a trezor-agent shell, it made the agent crash on an assertion error in the _legacy_pubs method in protocol.py

I'm using ubuntu linux, capistrano communicates with trezor-agent via a unix socket.

It seems the _legacy_pubs expects the buffer to be empty otherwise it refuses to continue, but I don't know why.

When capistrano tried to connect to the trezor-agent the contents in 'buf' were as follows:

(Pdb) list
 61  	
 62  	
 63  	def _legacy_pubs(buf):
 64  	    """SSH v1 public keys are not supported."""
 65  	    import pdb; pdb.set_trace()
 66  ->	    assert not buf.read()
 67  	    code = util.pack('B', msg_code('SSH_AGENT_RSA_IDENTITIES_ANSWER'))
 68  	    num = util.pack('L', 0)  # no SSH v1 keys
 69  	    return util.frame(code, num)
 70  	
 71  	
(Pdb) buf.read()
'\x00\x00\x00(SSH-2.0-Ruby/Net::SSH_4.1.0 x86_64-linux'

Just removing that check made everything work for me. I'm guessing it was added to deal with quirks on other platforms (?). 

I don't expect this pull request to get merged though, just get the conversation going, as I'm not really sure about what I've just removed. Maybe there's some configuration in capistrano that won't make it use the legacy_pubs method.

Best regards.
----nubis

### CODE REVIEW

**Comment by romanz** [comment]
Thanks for opening this PR!
You did the correct fix for the problem :)
I'll merge it tomorrow...

**Comment by nubis** [comment]
Awesome! Seems I got lucky.
Not sure why travis failed tough.

**Comment by romanz** [comment]
There was a small issue with the unittests - I fixed and merged it at #100 :)
Thanks @nubis!

**Comment by romanz** [comment]
A new version containing this fix ([0.8.3](https://pypi.python.org/pypi/trezor_agent/0.8.3)) is pushed to PyPI. Thanks again :)

**Pull request closed without merging**
