### PR TITLE
Handle usupported extensions, fixes #383 fixes #379

### LINKED ISSUE #379: [Error] Load key [...] invalid format
Hello here!

Today I have an issue using the Ledger Nano to log in using the ledger-agent. It worked without issues until 3-4 days ago.

```
2022-02-28 10:13:01,816 WARNING      error: 27                                                                                            [server.py:100]
Traceback (most recent call last):
  File "/home/[REDACTED]/.local/lib/python3.10/site-packages/libagent/server.py", line 95, in handle_connection
    reply = handler.handle(msg=msg)
  File "/home/[REDACTED]/.local/lib/python3.10/site-packages/libagent/ssh/protocol.py", line 98, in handle
    log.warning('Unsupported command: %s (%d)', msg_name(code), code)
  File "/home/[REDACTED]/.local/lib/python3.10/site-packages/libagent/ssh/protocol.py", line 54, in msg_name
    return ids[code]
KeyError: 27
Load key "/tmp/trezor-ssh-pubkey-5pcf4wio": invalid format
[REDACTED]@[REDACTED]'s password
```

Any ideas what I could look at?

Thanks

### LINKED ISSUE #383: Key error while connecting.
Hello, I am getting this error while trying to connect over ssh using trezor. The device doesn't ask me to confirm the acction and ssh falls back to password authorization.
```
  File "/app/lib/python3.9/site-packages/libagent/server.py", line 95, in handle_connection
    reply = handler.handle(msg=msg)
  File "/app/lib/python3.9/site-packages/libagent/ssh/protocol.py", line 98, in handle
    log.warning('Unsupported command: %s (%d)', msg_name(code), code)
  File "/app/lib/python3.9/site-packages/libagent/ssh/protocol.py", line 54, in msg_name
    return ids[code]
KeyError: 27
```

### PR DESCRIPTION
**Pull request by yanchenko-igor**

### CODE REVIEW

**Comment by yanchenko-igor** [comment]
According to https://tools.ietf.org/id/draft-miller-ssh-agent-02.html#rfc.section.4.7
Extension failure should be signaled using the SSH_AGENT_EXTENSION_FAILURE code - extensions should not use the standard SSH_AGENT_FAILURE message. This allows failed requests to be distinguished from the extension not being supported.

**Comment by mavaa** [comment]
Thanks a lot, this fixes the issue for me! Tested on Arch Linux with OpenSSH v8.9p1-1
Fixes #379 which I believe is the same issue as #383 (?)

**Comment by yanchenko-igor** [comment]
> Fixes #379 which I believe is the same issue as #383 (?)
You are right.

**Comment by mavaa** [comment]
There seems to be an issue for me still. After upgrading my arch server, I started getting a new error, and it seems like it happens only if both client and server is on openssh 8.9:
```
2022-03-24 09:49:12,584 ERROR        signature with "<ssh://serverhostname|nist256p1>" key failed                                                [protocol.py:151]
Traceback (most recent call last):
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/protocol.py", line 147, in sign_message
    signature = self.conn.sign(blob=blob, identity=key['identity'])
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/__init__.py", line 234, in sign
    return conn.sign_ssh_challenge(blob=blob, identity=identity)
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/client.py", line 35, in sign_ssh_challenge
    msg = parse_ssh_blob(blob)
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/client.py", line 79, in parse_ssh_blob
    assert not i.read()
AssertionError
sign_and_send_pubkey: signing failed for ECDSA "/home/myuser/.ssh/serverhostname.pub" from agent: communication with agent failed
myuser@server-ip: Permission denied (publickey).
2022-03-24 09:49:12,585 WARNING      error:                                                                                               [server.py:100]
Traceback (most recent call last):
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/server.py", line 95, in handle_connection
    reply = handler.handle(msg=msg)
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/protocol.py", line 106, in handle
    reply = method(buf=buf)
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/protocol.py", line 147, in sign_message
    signature = self.conn.sign(blob=blob, identity=key['identity'])
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/__init__.py", line 234, in sign
    return conn.sign_ssh_challenge(blob=blob, identity=identity)
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/client.py", line 35, in sign_ssh_challenge
    msg = parse_ssh_blob(blob)
  File "/external/myuser/src/tools/trezor-agent/repo/libagent/ssh/client.py", line 79, in parse_ssh_blob
    assert not i.read()
AssertionError
```

Could very well be a misconfiguration on my side. I've tested a few configurations, but not looked to much into the assertion and code it trezor-agent.

8.8 Client -> 8.8 Server: Works ✅ 
8.9 Client -> 8.8 Server: Works ✅ 
8.8 Client -> 8.9 Server: Works ✅ 
8.9 Client -> 8.9 Server: Doesn't work, fails with the error above 🔴

**Comment by yanchenko-igor** [comment]
@mavaa  It seems to be a separate issue, could you please create another issue for this error and I will try to figure out.

**Comment by Math3mat1x** [comment]
@romanz Will you merge this PR?

**Review by romanz — APPROVED** [review]
Many thanks, sorry for the (very) delayed response!

**Pull request merged**
