### PR TITLE
better handling of keepkey dependency

### LINKED ISSUE #36: Poor Python 3 support
The tests are passing for Py3 although when I run `trezor-gpg agent` I get this:

```traceback
Traceback (most recent call last):
  File "/home/minder/.virtualenvs/trezor/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.7.0', 'console_scripts', 'trezor-gpg')()
  File "/home/minder/.virtualenvs/trezor/lib/python3.5/site-packages/trezor_agent/gpg/__main__.py", line 95, in main
    args.run(args)
  File "/home/minder/.virtualenvs/trezor/lib/python3.5/site-packages/trezor_agent/gpg/__main__.py", line 65, in run_agent
    sock_path = keyring.get_agent_sock_path()
  File "/home/minder/.virtualenvs/trezor/lib/python3.5/site-packages/trezor_agent/gpg/keyring.py", line 18, in get_agent_sock_path
    lines = sp.check_output(['gpgconf', '--list-dirs']).strip().split('\n')
TypeError: a bytes-like object is required, not 'str'
```

Nevertheless I'm working on a solution :smile:

### PR DESCRIPTION
**Pull request by dekoza**
fixes #36

### CODE REVIEW

**Comment by dekoza** [comment]
Whoops, need to fix according to tests, sorry.

**Comment by dekoza** [comment]
Right now the agent runs on Python3 using trezorlib only. Keepkey is Py2-only. We probably should warn user about this.

**Comment by dekoza** [comment]
Hold that, I'm getting more errors. We need to make more integration tests.

**Comment by romanz** [comment]
Many thanks for the contributions :)
Really appreciate it!

**Pull request merged**
