### PR TITLE
Add OnlyKey support

### PR DESCRIPTION
**Pull request by romanz**
Following #332

### CODE REVIEW

**Comment by romanz** [comment]
@onlykey I have done a small refactoring in https://github.com/romanz/trezor-agent/pull/337/commits/a12202d80902760bbc99bef766986e0c450564d4 and removed RSA support (for this PR - let's add it separately).
Please review :)

**Comment by onlykey** [comment]
@romanz I will test this out again to make sure everything is good and let you know this week.

**Comment by lhindir** [comment]
Were you able to take a look @onlykey?

**Comment by cr7pt0** [comment]
@romanz Apologies for the delay, I tested everything out and working very well. This is good to release.

**Comment by onlykey** [comment]
@romanz Apologies for the delay, I tested this out and all is working very well. This is ready to release.

**Pull request merged**
