### PR TITLE
Support SSH signatures

### PR DESCRIPTION
**Pull request by romanz**
https://www.agwa.name/blog/post/ssh_signatures

See here for more details:
https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.sshsig
https://github.com/openssh/openssh-portable/blob/master/sshsig.c
https://github.com/openssh/openssh-portable/commit/2a9c9f7272c1e8665155118fe6536bebdafb6166

### CODE REVIEW

**Comment by romanz** [comment]
Tested locally:
```
$ trezor-agent -e ed25519 git@github.com | tee ~/.ssh/trezor-github.pub
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIvcbhXyaXXNytCLTDfEMlLuwEhtfo0XmPP1U5RsnOZ4 <ssh://git@github.com|ed25519>


$ trezor-agent -e ed25519 git@github.com -- ssh-keygen -vvvvv -Y sign -f ~/.ssh/trezor-github.pub -n file README.md
Signing file README.md
debug2: hash_file: hashed 3379 bytes
debug3: hash_file: final hash: 72b772fe4de577f023771d626cca096f3d90b639d13a757be5e4f1b1a843b8fc4d919f12a81d60008438433c858ef06fda62dc51cef2dac3aea91e2585cde327
Write signature to README.md.sig

$ cat allowed 
git@github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIvcbhXyaXXNytCLTDfEMlLuwEhtfo0XmPP1U5RsnOZ4 <ssh://git@github.com|ed25519>

$ ssh-keygen -Y verify -f allowed -I git@github.com -n file -s README.md.sig < README.md
Good "file" signature for git@github.com with ED25519 key SHA256:6UBhPb5SOoCUfasGC1/aCBegYov0/P3ajd6eNbYg77A
```

**Comment by geneotech** [comment]
Thanks for your hard work! :wave: Any chance this could work for Ledger Nano S? I'm running the commands just like in your local test, but with ledger-agent instead of trezor-agent and it appears to break the connection just before signing the test ``README.md``. Here is what I get (I've enabled ``logging.DEBUG`` on ``ledger.py, formats.py, server.py`` and ``protocol.py`` for troubleshooting):

```
/home/pbc/signexp>ledger-agent -e ed25519 git@github.com | tee ~/.ssh/ledger-github.pub
2022-05-17 23:34:19,130 DEBUG        apdu: b'\x80\x02\x00\x02\x15\x05\x80\x00\x00\r\xf7\xf6L\xee\xf9<\x17\x02\xdd\xcf=\xd8\xc6\x9e\xd7|'  [ledger.py:65]
2022-05-17 23:34:24,131 DEBUG        result: bytearray(b'A\x04,\x01\xa7\xff~r\xa2\x12K(\x1c\x81\xc9%\xa9+\xa0\xaa\x01\\"%\xce\xf4\xc9cd\xc8-~\xd7\x830s\xe4)\x0e
\xce\x8e\x14\x95WY:\xdb\x8b\x94\xc6\x87\xc8\x13\xab\x8d7\xa7\x07\xa62\xa8%k%\x8e\xe5') [ledger.py:67]
2022-05-17 23:34:24,131 DEBUG        fingerprint: 75:bc:9f:9c:0f:6c:2a:a4:6d:92:d9:5f:90:80:5c:cf                                         [formats.py:211]
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOWOJWslqDKmB6c3jasTyIfGlIvbOllXlRSOzg4p5HOw <ssh://git@github.com|ed25519>
/home/pbc/signexp>ledger-agent -e ed25519 git@github.com -- ssh-keygen -vvv -Y sign -f ~/.ssh/ledger-github.pub -n file README.md
2022-05-17 23:34:31,887 DEBUG        serving on /tmp/trezor-ssh-agent-dnlyz16u                                                            [server.py:30]
2022-05-17 23:34:31,888 DEBUG        server thread started                                                                                [server.py:121]
2022-05-17 23:34:31,888 INFO         running ['ssh-keygen', '-vvv', '-Y', 'sign', '-f', '/home/pbc/.ssh/ledger-github.pub', '-n', 'file', 'README.md'] with {'SS
H_AUTH_SOCK': '/tmp/trezor-ssh-agent-dnlyz16u', 'SSH_AGENT_PID': '30021'} [server.py:156]
2022-05-17 23:34:31,888 DEBUG        waiting for connection on /tmp/trezor-ssh-agent-dnlyz16u                                             [server.py:129]
2022-05-17 23:34:31,889 DEBUG        subprocess 30025 is running                                                                          [server.py:163]
2022-05-17 23:34:31,891 DEBUG        welcome agent                                                                                        [server.py:90]
2022-05-17 23:34:31,891 DEBUG        waiting for connection on /tmp/trezor-ssh-agent-dnlyz16u                                             [server.py:129]
2022-05-17 23:34:31,891 DEBUG        request: 1 bytes                                                                                     [protocol.py:97]
2022-05-17 23:34:31,891 DEBUG        calling list_pubs()                                                                                  [protocol.py:105]
2022-05-17 23:34:31,985 DEBUG        apdu: b'\x80\x02\x00\x02\x15\x05\x80\x00\x00\r\xf7\xf6L\xee\xf9<\x17\x02\xdd\xcf=\xd8\xc6\x9e\xd7|'  [ledger.py:65]
2022-05-17 23:34:39,452 DEBUG        result: bytearray(b'A\x04,\x01\xa7\xff~r\xa2\x12K(\x1c\x81\xc9%\xa9+\xa0\xaa\x01\\"%\xce\xf4\xc9cd\xc8-~\xd7\x830s\xe4)\x0e
\xce\x8e\x14\x95WY:\xdb\x8b\x94\xc6\x87\xc8\x13\xab\x8d7\xa7\x07\xa62\xa8%k%\x8e\xe5') [ledger.py:67]
2022-05-17 23:34:39,452 DEBUG        fingerprint: 75:bc:9f:9c:0f:6c:2a:a4:6d:92:d9:5f:90:80:5c:cf                                         [formats.py:211]
2022-05-17 23:34:39,549 DEBUG        loading SSH public key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOWOJWslqDKmB6c3jasTyIfGlIvbOllXlRSOzg4p5HOw <ssh://git@github
.com|ed25519>\n' [formats.py:218]
2022-05-17 23:34:39,549 DEBUG        key type: b'ssh-ed25519'                                                                             [formats.py:58]
2022-05-17 23:34:39,549 DEBUG        loaded ssh-ed25519 public key: 75:bc:9f:9c:0f:6c:2a:a4:6d:92:d9:5f:90:80:5c:cf                       [formats.py:224]
2022-05-17 23:34:39,549 DEBUG        available keys: [b'<ssh://git@github.com|ed25519>']                                                  [protocol.py:117]
2022-05-17 23:34:39,549 DEBUG         1) 75:bc:9f:9c:0f:6c:2a:a4:6d:92:d9:5f:90:80:5c:cf                                                  [protocol.py:119]
2022-05-17 23:34:39,549 DEBUG        reply: 98 bytes                                                                                      [protocol.py:108]
Signing file README.md
debug2: hash_file: hashed 3076 bytes
debug3: hash_file: final hash: 389da307b6a02a1b6a667ccc3f433bd1238a13c1051870af68a6701902e0231d4eceabb067ab5121874ba6a74af1b365a962175fd8449b39210a56722aa9677e
2022-05-17 23:34:39,549 DEBUG        request: 160 bytes                                                                                   [protocol.py:97]
2022-05-17 23:34:39,549 DEBUG        calling sign_message()                                                                               [protocol.py:105]
2022-05-17 23:34:39,549 DEBUG        key type: b'ssh-ed25519'                                                                             [formats.py:58]
2022-05-17 23:34:39,549 DEBUG        looking for 75:bc:9f:9c:0f:6c:2a:a4:6d:92:d9:5f:90:80:5c:cf                                          [protocol.py:131]
2022-05-17 23:34:39,549 DEBUG        loading SSH public key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOWOJWslqDKmB6c3jasTyIfGlIvbOllXlRSOzg4p5HOw <ssh://git@github
.com|ed25519>\n' [formats.py:218]
2022-05-17 23:34:39,549 DEBUG        key type: b'ssh-ed25519'                                                                             [formats.py:58]
2022-05-17 23:34:39,549 DEBUG        loaded ssh-ed25519 public key: 75:bc:9f:9c:0f:6c:2a:a4:6d:92:d9:5f:90:80:5c:cf                       [formats.py:224]
2022-05-17 23:34:39,550 DEBUG        using key b'<ssh://git@github.com|ed25519>' (75:bc:9f:9c:0f:6c:2a:a4:6d:92:d9:5f:90:80:5c:cf)        [protocol.py:138]
2022-05-17 23:34:39,550 DEBUG        signing 96-byte blob with "<ssh://git@github.com|ed25519>" key                                       [protocol.py:145]
2022-05-17 23:34:39,642 DEBUG        apdu: b'\x80\x04\x00\x82u\x05\x80\x00\x00\r\xf7\xf6L\xee\xf9<\x17\x02\xdd\xcf=\xd8\xc6\x9e\xd7|SSHSIG\x00\x00\x00\x04file\x
00\x00\x00\x00\x00\x00\x00\x06sha512\x00\x00\x00@8\x9d\xa3\x07\xb6\xa0*\x1bjf|\xcc?C;\xd1#\x8a\x13\xc1\x05\x18p\xafh\xa6p\x19\x02\xe0#\x1dN\xce\xab\xb0g\xabQ!\x
87K\xa6\xa7J\xf1\xb3e\xa9b\x17_\xd8D\x9b9!\nVr*\xa9g~' [ledger.py:90]
2022-05-17 23:34:39,655 DEBUG        result: bytearray(b'')                                                                               [ledger.py:92]
2022-05-17 23:34:39,674 DEBUG        signature: b''                                                                                       [protocol.py:154]
Couldn't sign message (signer): communication with agent failed
Signing README.md failed: communication with agent failed
2022-05-17 23:34:39,674 WARNING      error:                                                                                               [server.py:100]
Traceback (most recent call last):
  File "/home/pbc/rep/trezor-agent/libagent/server.py", line 95, in handle_connection
    reply = handler.handle(msg=msg)
  File "/home/pbc/rep/trezor-agent/libagent/ssh/protocol.py", line 106, in handle
    reply = method(buf=buf)
  File "/home/pbc/rep/trezor-agent/libagent/ssh/protocol.py", line 157, in sign_message
    sig_bytes = key['verifier'](sig=signature, msg=blob)
  File "/home/pbc/rep/trezor-agent/libagent/formats.py", line 110, in ed25519_verify
    assert len(sig) == 64
AssertionError
2022-05-17 23:34:39,674 DEBUG        subprocess 30025 exited: 255                                                                         [server.py:165]
2022-05-17 23:34:39,749 DEBUG        server stopped                                                                                       [server.py:133]
2022-05-17 23:34:39,749 DEBUG        server thread stopped                                                                                [server.py:138]
/home/pbc/signexp>
```

The reason that ```assert len(sig) == 64``` fails is because ``sig`` is actually empty and returns a len of ``0``.

It appears that the device's response to the sign request (the second command) is **empty** - as opposed to the first request which just exposes the public key. Are you sure the ``apdu`` for the second request is correct? Shouldn't ``ps2`` be ``02`` instead of ``82`` (tried changing this but didn't help either).

I've tried running the tests provided with the ssh agent app from Ledger itself:
https://github.com/LedgerHQ/app-ssh-agent/blob/master/tests.py 
But they actually fail on ``TestSignSSHBlob`` and several others... which doesn't inspire confidence.

**Comment by geneotech** [comment]
Anyways, it's not a priority or anything, I just bought Trezor and the signing of arbitrary blobs works excellent, as per your local test :) Looks like it was a hardware issue after all.

**Comment by romanz** [comment]
The following snippet can be used to verify ad-hoc signatures:

```
function ssh-verify() {
    USERID=$1
    KEYTYPE=$2
    PUBKEY=$3
    SIGFILE=$4
    MSGFILE=$5    
    ssh-keygen -Y verify -f <(echo "\"$USERID\" $KEYTYPE $PUBKEY") \
               -I "$USERID" -n file -s "$SIGFILE" < "$MSGFILE"
}
```

For example:
```
$ ssh-verify \
    "USER ID" ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJC11jL3nsjv+hDvCxuW4C6BNDBOQ0I4J6NFJsNQkeah \
    README.md{.sig,}
Good "file" signature for USER ID with ED25519 key SHA256:UqB/Pct4g1zjkoyfuK5C/J6AHfuuoQVdh3VRbj/M+AQ
```

**Pull request merged**
